main: TCP UDP

TCP:
	gcc TCP_Client.c -o tcp_client
	gcc TCP_Server.c -o tcp_server
	
UDP:
	gcc UDP_Client.c -o udp_client
	gcc UDP_Server.c -o udp_server

clean:
	rm -rf tcp_client tcp_server udp_client udp_server
